server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location = /user { try_files /user.html =404; }

    location = /user/ { try_files /user.html =404; }

    location = /grafana {
        return 301 /grafana/;
    }

    location /grafana/ {
        proxy_pass http://cognitive-training-grafana:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Prefix /grafana;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_buffering off;
        proxy_read_timeout 180s;
    }
    location /api/ {
        proxy_pass http://cognitive-training-app:8091;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_buffering off;
        proxy_read_timeout 180s;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
